ui fixed & css working

diff --git a/ui/Dockerfile b/ui/Dockerfile
--- a/ui/Dockerfile
+++ b/ui/Dockerfile
@@ -1,16 +1,57 @@
-FROM node:16-alpine as builder
+FROM node:18-alpine AS base
+
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 
-ENV PORT 3000
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
+ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN mkdir -p /usr/src/app
-WORKDIR /usr/src/app
-COPY package*.json /usr/src/app/
-RUN npm install
-
-COPY . /usr/src/app
-
+# If using npm comment out above and use below instead
 RUN npm run build
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/next.config.js ./
+COPY --from=builder /app/public ./public
+COPY --from=builder /app/package.json ./package.json
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/_next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/_next/static ./_next/static
+
+
+
+
+USER nextjs
+ENV PORT 3000
 EXPOSE 3000
-CMD [ "npm", "run","start" ]
+
+CMD ["node", "server.js"]
